import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_macchiato.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family= "JetBrainsMono NF"
style="Regular"

[window.padding]
x = 0
y = 0
