import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
# size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 0
y = 0
