[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[language-server.rust-analyzer]
command = "rust-analyzer"
[language-server.rust-analyzer.config.check]
allTargets = false

[[language]]
name = "cpp"
file-types = ["cpp", "h", "hpp"]
roots = [".ccls"]
auto-format = true
language-servers = ["cc-ls"]

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[language-server.cc-ls]
command = "ccls"

[language-server.clangd]
command = "clangd"

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "ini"
scope = "source.ini"
file-types = [
  "ini",
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = ".editorconfig" },
  { glob = "rclone.conf" },
  "properties",
  "cfg",
  "directory",

  # === your specific .conf files or all ".conf" files ===
  # { glob = "some_file.conf" },
  # "conf",
]
injection-regex = "ini"
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }

[[grammar]]
name = "ini"
source = { git = "https://github.com/justinmk/tree-sitter-ini", rev = "1b0498a89a1a4c0a3705846699f0b0bad887dd04" }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }
